# Generated by Django 5.0.6 on 2025-11-05 17:46

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='This field must contain exactly 11 digits.', regex='^\\d{11}$')])),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_borrowed', models.IntegerField()),
                ('borrowed_date', models.DateTimeField(default=datetime.datetime.now)),
                ('active', models.BooleanField(default=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='LibManager.book')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LibManager.member')),
            ],
        ),
    ]
