# Generated by Django 5.2.8 on 2025-11-05 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibManager', '0002_member_bookloan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LibManager.book'),
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibManager.member'),
        ),
    ]
