# Generated by Django 5.2.8 on 2025-11-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibManager', '0003_alter_bookloan_book_alter_bookloan_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookloan',
            name='active',
        ),
        migrations.AddField(
            model_name='bookloan',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
